# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 84573862c68fee9c5f50d3527d3ece281fa09e021b7378818c82a810b5f1c3c1ef2e1e1fad29a2645a34bb2d08393cc0b67a00b4777398c3e309cb86868f411b

test:
  secret_key_base: ff1f2ae31c56b9cfefed49e94e2ca9744f6520f0aee8c7dd4de3c1eb27854d566a3bdcf94dd43580b035e3c9dc531f264a611760a8a14cefec217f7e8e7c1a19

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
